<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $title }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 10px; color: #333; padding: 20px; }
        .header { text-align: center; margin-bottom: 30px; padding-bottom: 15px; border-bottom: 2px solid #4F46E5; }
        .header h1 { font-size: 24px; color: #4F46E5; margin-bottom: 5px; }
        .header .meta { font-size: 9px; color: #666; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        thead { background-color: #4F46E5; color: white; }
        thead th { padding: 10px 8px; text-align: center; font-weight: 600; font-size: 10px; text-transform: uppercase; }
        tbody tr { border-bottom: 1px solid #E5E7EB; }
        tbody tr:nth-child(even) { background-color: #F9FAFB; }
        tbody td { padding: 8px; font-size: 9px; text-align: center; vertical-align: middle; }
        .footer { margin-top: 30px; padding-top: 15px; border-top: 1px solid #E5E7EB; text-align: center; font-size: 8px; color: #666; }
        .no-data { text-align: center; padding: 40px; color: #999; font-style: italic; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <div class="meta">Generated on: {{ $generatedAt }}</div>
    </div>

    @if(count($rows) > 0)
        <table>
            <thead>
                <tr>
                    <th>UUID</th>
                    <th>Title</th>
                    <th>Slug</th>
                    <th>Category</th>
                    <th>Status</th>
                    <th>Published At</th>
                    <th>Created At</th>
                </tr>
            </thead>
            <tbody>
                @foreach($rows as $row)
                    <tr>
                        <td>{{ $row['uuid'] }}</td>
                        <td>{{ $row['title'] }}</td>
                        <td>{{ $row['slug'] }}</td>
                        <td>{{ $row['category'] }}</td>
                        <td>{{ $row['status'] }}</td>
                        <td>{{ $row['published_at'] }}</td>
                        <td>{{ $row['created_at'] }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="no-data">No posts found matching the specified criteria.</div>
    @endif

    <div class="footer">
        <p>This document was automatically generated by the system.</p>
        <p>Total records: {{ count($rows) }}</p>
    </div>
</body>
</html>
